image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      gem install rails -v 7.2.2 &&
      rails new . --skip-bundle --database=postgresql
  - command: |
      sudo service postgresql start &&
      cp config/database.yml config/database.yml.bak &&
      sed -i 's/username: .*/username: gitpod/' config/database.yml &&
      sed -i 's/password: .*/password:/' config/database.yml &&
      bundle install &&
      bin/rails db:create db:migrate &&
      bin/rails server -b 0.0.0.0

ports:
  - port: 3000
    onOpen: open-preview

