image: gitpod/workspace-full

tasks:
  - init: >
      gem install rails -v 7.1.3 &&
      rails new . --skip-bundle --database=sqlite3
  - command: |
      bundle install &&
      bin/rails db:migrate &&
      bin/rails server -b 0.0.0.0

ports:
  - port: 3000
    onOpen: open-preview
