image: gitpod/workspace-full

tasks:
  - init: >
      sudo apt-get update &&
      sudo apt-get install -y libpq-dev &&
      gem install rails -v 7.1.3 &&
      rails new . --skip-bundle --database=postgresql
  - command: |
      cp config/database.yml config/database.yml.bak &&
      sed -i 's/username: .*/username: gitpod/' config/database.yml &&
      sed -i 's/password: .*/password:/' config/database.yml &&
      bundle install &&
      bin/rails db:create db:migrate &&
      bin/rails server -b 0.0.0.0

ports:
  - port: 3000
    onOpen: open-preview
